export const plansActionTypes = {
  PLANS_START_ADD: "[PLANS] START NEW PLAN",
  PLANS_ADD_NEW: "[PLANS] NEW PLAN",
  PLANS_ACTIVE: "[PLANS] SET ACTIVE PLAN",
  PLANS_LOAD: "[PLANS] LOAD PLANS",
  PLANS_START_DELETE: "[PLANS] START DELETE",
  PLANS_UPDATE: "[PLANS] UPDATE PLAN",
  PLANS_DELETE: "[PLANS] DELETE PLAN ",
  PLANS_LOGOUT_CLEANING: "[PLANS] LOGOUT CLEANING",
};
